githubConfigSecret: rrflow-arc-github
runnerScaleSetName: rrflow-standard
runnerGroup: default
minRunners: 0
maxRunners: 2

controllerServiceAccount:
  namespace: arc-systems
  name: arc-gha-rs-controller

listenerTemplate:
  spec:
    containers:
      - name: listener
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

template:
  metadata:
    labels:
      rrflow.io/runner-class: standard
  spec:
    automountServiceAccountToken: false
    nodeSelector:
      kubernetes.io/arch: amd64
      kubernetes.io/os: linux
    securityContext:
      seccompProfile:
        type: RuntimeDefault
    terminationGracePeriodSeconds: 30
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner@sha256:5036480998280bb21e32ade9fe1b02b493861ac314b62ba1aea320b94f56ec97
        command:
          - /home/runner/run.sh
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: "16"
            memory: 20Gi
          limits:
            cpu: "16"
            memory: 20Gi
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
    volumes:
      - name: work
        emptyDir: {}
